# Generated by Django 5.1.4 on 2025-02-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='icecream_images/'),
        ),
    ]
